# -*- coding: utf-8 -*-
"""Exercise_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTAkni50jciE1qszfssnoxYNp3BvauM1
"""

try:
    with open("student.txt", "r") as file:
        data = file.read()
        print(data)
except FileNotFoundError:
    print("File not found.")