# -*- coding: utf-8 -*-
"""Exercise_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTAkni50jciE1qszfssnoxYNp3BvauM1
"""

name = input("Enter student name: ")
roll = input("Enter roll number: ")
marks = input("Enter marks: ")

with open("student.txt", "w") as file:
    file.write(f"Name: {name}\n")
    file.write(f"Roll No: {roll}\n")
    file.write(f"Marks: {marks}\n")

print("Student details saved successfully.")