# -*- coding: utf-8 -*-
"""Exercise_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTAkni50jciE1qszfssnoxYNp3BvauM1
"""

try:
    a = int(input("Enter numerator: "))
    b = int(input("Enter denominator: "))

    result = a / b
    print("Result =", result)

except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")