# -*- coding: utf-8 -*-
"""Exercise_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygIqZ6vVF5h90dfI-QRCk25nOVRjr-A9
"""

# Find square and cube

number = int(input("Enter a number: "))

square = number ** 2
cube = number ** 3

print("Square =", square)
print("Cube =", cube)