# -*- coding: utf-8 -*-
"""Exercise_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygIqZ6vVF5h90dfI-QRCk25nOVRjr-A9
"""

# Calculate Simple Interest

principal = float(input("Enter principal amount: "))
rate = float(input("Enter rate of interest: "))
time = float(input("Enter time (years): "))

simple_interest = (principal * rate * time) / 100

print("Simple Interest =", simple_interest)