# -*- coding: utf-8 -*-
"""Exercise_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygIqZ6vVF5h90dfI-QRCk25nOVRjr-A9
"""

# Calculate average of three numbers

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))

average = (num1 + num2 + num3) / 3

print("Average =", average)