# -*- coding: utf-8 -*-
"""Exercise_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygIqZ6vVF5h90dfI-QRCk25nOVRjr-A9
"""

# Find area of a rectangle

length = float(input("Enter length: "))
width = float(input("Enter width: "))

area = length * width

print("Area of rectangle =", area)