# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Yq8d_4yPR7GyleVLSOy-8OTePZAVUOi
"""

#Assignment2 given on June 3rd, 2026 (Wednesday)
#Submitted by Tiya Singh, CSE-3, 20701012025, IGDTUW 2029

#Find sum of first 10 natural numbers.

num=10
if num<0:
  print("Enter a positive number")
else:
  sum=0
  while (num>0):
    sum+=num
    num-=1
  print("The sum of first 10 natural numbers is", sum)

#Find factorial of a number.

num=int(input("Enter a number: "))
factorial=1
if num<0:
  print("Enter a positive number")
elif num==0:
  print("Factorial of 0 is 1")
else:
  for i in range(1, num+1):
    factorial*=i
  print("Factorial of number entered is", factorial)

#Print Fibonacci Series.

n=int(input("Enter number of terms for Fibonacci Series: "))
n1,n2=0,1
count=0
if n<=0:
  print("Enter a positive number.")
elif n==1:
  print("Fibonacci sequence upto", n, ":")
  print(n1)
else:
  print("Fibonacci sequence upto", n, ":")
  while count<n:
    print(n1)
    next=n1+n2
    n1=n2
    n2=next
    count+=1

#Find largest among 3 numbers.

a=float(input("Enter first number: "))
b=float(input("Enter second number: "))
c=float(input("Enter third number: "))
if a>=b and a>=c:
  largest=a
elif b>=a and b>=c:
    largest=b
else:
    largest=c
print("The largest number is", largest)

#Create Student Result System
#Input student details, marks, Calculate percentage, Display grade
#Use: if-elif-else, loops

name=input("Enter Student Name: ")
rno=int(input("Enter Roll Number: "))
m1=float(input("Enter marks for Subject 1 (out of 100): "))
m2=float(input("Enter marks for Subject 2 (out of 100): "))
m3=float(input("Enter marks for Subject 3 (out of 100): "))
m4=float(input("Enter marks for Subject 4 (out of 100): "))
m5=float(input("Enter marks for Subject 5 (out of 100): "))

total=m1+m2+m3+m4+m5
percentage=(total/500)*100

if percentage >= 93:
    grade = "A+"
elif percentage >= 85:
    grade = "A"
elif percentage >= 77:
    grade = "B"
elif percentage >= 69:
    grade = "C"
elif percentage >= 61:
    grade = "D"
else:
    grade = "F"

print("Student Name: ", name)
print("Roll Number: ", rno)
print("Total Marks: ", total)
print("Percentage: ", percentage)
print("Grade: ", grade)