# -*- coding: utf-8 -*-
"""Copy of Assignment3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qqNqvW6mZMfWyWNI_5dNjynv0pjccIhW
"""

#Q1 Create a function to print first 10 natural numbers.
#Defining the function
def natural_numbers(num):
  for i in range(1,num+1):
    print(i)

#Calling the funcion
print(natural_numbers(10))

#Q2 Create a function to calculate sum of first N natural numbers.
#Defining the function
N=int(input("Enter the number:"))
def cal_sum(num):

  sum=0
  for i in range(1,num+1):
    sum+=i
  print(sum)

#Calling the function
print(cal_sum(N))

#Q3 Create a function to reverse a number.
N=int(input("Enter the number:"))
#Defining the function
def reverse_number(num):
  return int(str(num)[::-1])

#Calling the function
print(reverse_number(N))

#Q4 Create a function to count digits in a number.
N=int(input("Enter the number:"))
#Defining the function
def count_digits(num):
  return len(str(num))

print(count_digits(N))

#Q5 Create a function to check palindrome number.
N=int(input("Enter the number:"))
#Defining the function
def check_palindrome(num):
  rev_num=int(str(num)[::-1])
  if(rev_num==num):
    print("The given number is a palindrome number.")
  else:
    print("The given number is not a palindrome number.")

#Calling the function
print(check_palindrome(N))

#Q6 Create a function to generate Fibonacci series
N=int(input("Enter the number:"))
#Defining the function
def fibonacci_series(num):
  a,b=0,1
  for i in range(num+1):
    print(a,end=" ")
    a,b=b,a+b

print(fibonacci_series(N))

#Q7 Calulator using functions
def add(a,b):
  return a+b
def subtract(a,b):
  return a-b
def multiply(a,b):
  return a*b
def divide(a,b):
  if (b!=0):
    return a/b
  else:
    return "division by zero is not allowed"

print("Calculator")
print("1.Addition")
print("2.Subtraction")
print("3.Multiplicatioh")
print("4.Division")

select=int(input("Enter your choice(1-4):"))
num_1=float(input("Enter first number:"))
num_2=float(input("Enter second number:"))

if (select==1):
  print("Result=",add(num_1,num_2))
elif(select==2):
  print("Result=",sub(num_1,num_2))
elif(select==3):
  print("Result=",multiply(num_1,num_2))
elif(select==42):
  print("Result=",divide(num_1,num_2))
else:
  print("Invalid choice")

#Q8 Create a text file and store student's details.
#creating and opening file in write mode
file=open("student.txt","w")

name=input("Enter student's name:")
age=(input("Enter student's age:"))
percentage=(input("Enter studentt's percentage:"))

#storing student's details in file
file.write("Name:"+name+"\n")
file.write("Age:"+age+"\n")
file.write("Percentage:"+percentage+"%"+"\n")

#closing the file
file.close()

print("student details saved successfully.")

#Q9 Read data from a file.
#Reading the data stored in previous file
file=open("student.txt","r")
#storing file data into a variable
data=file.read()
print(data)
file.close()

#Q10 Handle division by zero using exception handling.
try:
  num1=int(input("Enter first number:"))
  num2=int(input("Enter second number:"))
  result=num1/num2
  print("Result=",result)

except ZeroDivisionError:
  print("Error:Division by zero is not allowed.")

finally:
  print("Program ended.")

#Q11 Create a student class with name and marks.
#Creating the class
class student:
  def __init__(self,name,marks):
    self.name=name
    self.marks=marks

  def display(self):
    print("Name:",self.name)
    print("Marks:",self.marks)

name=input("enter student's name:")
marks=float(input("enter student's marks:"))

#Creating an object
s1=student(name,marks)
#Displaying result
s1.display()