# -*- coding: utf-8 -*-
"""Week1_Exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQyD-4JCdwTLWWVVqq9ivmE1FohvT_uU
"""

# Assignment 1
# Question 1: Find Area of Rectangle
# Area of Rectangle

length = float(input("Enter length: "))
breadth = float(input("Enter breadth: "))

area = length * breadth

print("Area =", area)

# Question 2: Find Simple Interest
# Simple Interest

p = float(input("Enter principal: "))
r = float(input("Enter rate: "))
t = float(input("Enter time: "))

si = (p*r*t)/100

print("Simple Interest =", si)

# Question 3: Convert Celsius to Fahrenheit
# Celsius to Fahrenheit

c = float(input("Enter Celsius: "))

f = (c*9/5)+32

print("Fahrenheit =", f)

# Question 4: Average of 3 Numbers
# Average of 3 numbers

a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
c = float(input("Enter third number: "))

avg = (a+b+c)/3

print("Average =", avg)

# Question 5: Square and Cube
# Square and Cube

num = float(input("Enter number: "))

print("Square =", num**2)
print("Cube =", num**3)

# Question 6: Swap Two Numbers
# Swapping without third variable

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

a = a+b
b = a-b
a = a-b

print("a =",a)
print("b =",b)

# Question 7: Student Report Program
# Student Report

name = input("Enter name: ")

m1 = float(input("Enter marks 1: "))
m2 = float(input("Enter marks 2: "))
m3 = float(input("Enter marks 3: "))

total = m1+m2+m3
percentage = (total/300)*100

print("Name:",name)
print("Total:",total)
print("Percentage:",percentage)