# -*- coding: utf-8 -*-
"""Exercise_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTAkni50jciE1qszfssnoxYNp3BvauM1
"""

def count_digits(num):
    count = 0

    while num > 0:
        count += 1
        num //= 10

    return count

num = int(input("Enter a number: "))
print("Number of digits:", count_digits(num))