# -*- coding: utf-8 -*-
"""Exercise_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTAkni50jciE1qszfssnoxYNp3BvauM1
"""

def print_natural_numbers():
    for i in range(1, 11):
        print(i)

print_natural_numbers()