# -*- coding: utf-8 -*-
"""Exercise_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTAkni50jciE1qszfssnoxYNp3BvauM1
"""

def sum_natural_numbers(n):
    return n * (n + 1) // 2

n = int(input("Enter N: "))
print("Sum =", sum_natural_numbers(n))