# -*- coding: utf-8 -*-
"""Exercise_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTAkni50jciE1qszfssnoxYNp3BvauM1
"""

def reverse_number(num):
    rev = 0

    while num > 0:
        digit = num % 10
        rev = rev * 10 + digit
        num //= 10

    return rev

num = int(input("Enter a number: "))
print("Reversed number:", reverse_number(num))