# -*- coding: utf-8 -*-
"""Assignment2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10A58eqBNlVR-VtYLsi1JuCOi8Odrf3O5
"""

#Q1 Find sum of first 10 natural numbers.
#Generating first 10 natural numbers using range() function
num=range(1,11)
#Calculating sum
sum=sum(num)
print("The sum of first 10 natural numbers is:",sum)

#Q2 Find factorial of a number.
num =int(input("Enter the number:"))

# Initializing the result variable to 1
factorial = 1

# Checking if the number is negative, zero, or positive
if num < 0:
    print("Factorial does not exist for negative numbers.")
elif num == 0:
    print("The factorial of 0 is 1.")
else:
    # Loop from 1 to num (num + 1 is exclusive)
    for i in range(1, num + 1):
        factorial *= i  # Equivalent to: factorial = factorial * i

    print(f"The factorial of {num} is {factorial}")

#Q3 Print Fibonacci Series
num=int(input("Enter the number:"))
a,b=0,1
print("Fibonacci series:")
for i in range(num):
  print(a,end=" ")
  a,b=b,a+b

#Q4 Find largest among 3 numbers.
#using conditional statements:
a=float(input("Enter 1st number:"))
b=float(input("Enter 2nd number:"))
c=float(input("Enter 3rd number:"))
if(a>=b and a>=c):
  print(a,"is the largest among 3 numbers.")
elif(b>=a and b>=c):
  print(b,"is the largest among 3 numbers.")
else:
  print(c,"is the largest among 3 numbers.")

#Q5 Create Student Result System
#Student details
name=input("Enter student's name:")
rollno=int(input("Enter student's rollno:"))

#inputing marks using loops
total=0
for i in range(5):
  marks=(float(input("Enter marks:")))
  total+=marks

print("Total marks:",total)
#Calculating percentage
per=total/5
print("Percentage:",per)
#Grade
if(total>=450):
  print("Grade:A+")

elif(total>=400):
  print("Grade:A")
elif(total>=350):
  print("Grade:B+")
else:
  print("Grade:B")