# -*- coding: utf-8 -*-
"""assignment 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L0g9GYllrkFFX3T5XvCMrcgbizbUAddR

Assignment 1 :
D Rasi Shree
05001012025
"""

# Find area of rectangle
n=int(input("enter lenght : "))
m=int(input("enter width : "))
print("Area : ", m*n)
# find Simple Interset
p=int(input("enter principle: "))
i=int(input("enter time: "))
r=int(input("enter rate in % "))
print("SI interst :",p*i*r*0.01)
# Calculate average of 3 numbers
p=int(input("enter num1 "))
i=int(input("enter num2 "))
r=int(input("enter num3 "))
print("Average : " ,(p+i+r)/3)
# Find square and cube of number
n=int(input("enter num1 "))
print("square : ",n*n, " cube : ",n**3)
# Swap two numbers without third variable
n=int(input("enter num1 "))
m=int(input("enter num2 "))
n=m+n
m=n-m
n=n-m
print("num1 :",n," num2 :",m)
# make student report and find total and average of marks
n=int(input("enter subject 1 "))
m=int(input("enter subject 2 "))
o=int(input("enter subject 3 "))
p=int(input("enter subject 4 "))
sum=n+m+o+p
print("Total : ",sum, " Average : ",sum/4)
