# -*- coding: utf-8 -*-
"""assignment 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-SYFsUjuIDISCI6a7jix5ccrXd59aTB
"""
# D Rasi Shree 05001012025
# Print first 10 natural numbers
def p():
  for i in range(1,11):
    print(i)
p()

#Sum of first n natural numbers
def s(n):
  sum=0
  for i in range(0,n+1):
    sum+=i
  print(sum)
s(5)

# Reverse the numbers
def rev(n):
  sum=0
  while(n):
    r=n%10
    sum=sum*10 +r
    n//=10
  print(sum)
rev(890)

# Count Digits
def d(n):
  i=0
  while(n):
    n//=10
    i+=1
  print(i)
d(789)

# Check Palindrome
def pal(n):
  s=str(n)
  if(s==s[::-1]):
    print("True")
  else:
    print("False")
pal(7896)

# Fibonacci series
def fab(n):
  a=0
  b=1
  while(n):
    print(a)
    temp=b
    b=a+b
    a=temp
    n-=1
fab(8)

# Calculator for 2 numbers
def cal():
  print("1: Add 2: Subtract 3: Multiply 4: Divide 5:Exit")
  ans=int(input("Enter option :"))
  if(ans==5):
    return
  n=int(input("enter num 1 "))
  m=int(input("enter num 2 "))
  if(ans==1):
    print(n+m)
  elif(ans==2):
    print(n-m)
  elif(ans==3):
    print(n*m)
  elif(ans==4):
    print(n/m)
  else:
    print("Wrong input")
  cal()
cal()

# Create and write to file
f = open("Student.txt", "w")
f.write("Hello parrot")
f.close()

# Read from file
f = open("Student.txt", "r")
content = f.read()
print(content)
f.close()

# Handel Zero Division error
try:
  n=int(input("Enter num 1 "))
  m=int(input("Enter num 2 "))
  print(n/m)
except ZeroDivisionError:
  print("Enter a non zero num2 ")
finally:
  print("Program completed ")

# Student class
class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def display(self):
        print("Name:", self.name)
        print("Marks:", self.marks)


# Create object
s1 = Student("Shree", 95)

# Display details
s1.display()
