# -*- coding: utf-8 -*-
"""Assignment 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeS-5e2YsMy8OT2QL-uyq-N7dldfBT16

Assignment 2
D Rasi Shree
05001012025
"""

# Find sum of first 10 natural numbers
for i in range (1,11):
  sum+=i
print("Sum : ",sum)
# Find factorial of number
n=int(input("Enter number"))
for i in range(1,n+1):
  fact*=i
print("Factorial : ",fact)
# Print Fabonacci series
n=int(input("Enter number : "))
a=0
b=1
for i in range(0,n):
  print(a)
  a=b
  b=a+b
# Print largest of 3 numbers
a=int(input("Enter num 1 : "))
b=int(input("Enter num 2 : "))
c=int(input("Enter num3 : "))
if(b>=a & b>=c):
  print(b)
elif(a>b & a>=c):
  print(c)
else:
  print(a)
#Create student result system
n=input("Enter name ")
m1=int(input("Enter sub 1 marks "))
m2=int(input("Enter sub 2 marks "))
m3=int(input("Enter sub 3 marks "))
m4=int(input("Enter sub 4 marks "))
sum=m1+m2+m3+m4
p=sum/4
print("Percentage : ",sum/4)
if(p>90):
  print("Grade : A")
elif(p>75):
  print("Grade : B")
else:
  print("Grade : C")
