# -*- coding: utf-8 -*-
"""assignmennt_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXkPT8y4Tb1DXCNOS8Aib5Vb7r8OEtrh
"""

# Print First 10 Natural Numbers

def printnumbers():
    for i in range(1, 11):
        print(i, end=" ")

printnumbers()

# Sum of First N Natural Numbers

def sumofn(n):
    sum = 0

    for i in range(1, n + 1):
        sum += i

    return sum

n = int(input("Enter N: "))
print("Sum =", sumofn(n))

# Reverse a Number

def reverse_number(num):
    reverse = 0

    while num > 0:
        digit = num % 10
        reverse = reverse * 10 + digit
        num = num // 10

    return reverse

num = int(input("Enter a Number: "))
print("Reverse =", reverse_number(num))

# Reversing a Number

def reversenumber(n):
    reverse = 0

    while n> 0:
        digit = n % 10
        reverse = reverse * 10 + digit
        n = n // 10

    return reverse

num = int(input("Enter a Number: "))
print("Reverse =", reversenumber(n))

# Reversing a Number

def reversenumber(num):
    reverse = 0

    while num > 0:
        digit = num % 10
        reverse = reverse * 10 + digit
        num = num // 10

    return reverse

num = int(input("Enter a Number: "))
print("Reverse =", reversenumber(num))

# Counting Digits in a number

def countdigits(num):
    count = 0

    while num > 0:
        count += 1
        num = num // 10

    return count

num = int(input("Enter a number= "))
print("Number of digits =", countdigits(num))

# Palindrome  Number

def ispalindrome(num):
    og = num
    reverse = 0

    while num > 0:
        digit = num % 10
        reverse = reverse * 10 + digit
        num = num // 10

    if og == reverse:
        return True
    else:
        return False

num = int(input("Enter a Number: "))

if ispalindrome(num):
    print("is a Palindrome")
else:
    print("Not a Palindrome ")

# Fibonacci Series

def fibonacci(n):
    a = 0
    b = 1

    for i in range(n):
        print(a, end=" ")
        c = a + b
        a = b
        b = c

n = int(input("Enter no. of terms "))
fibonacci(n)

# Calculator Using Functions

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    return a / b

print("1= Addition")
print("2= Subtraction")
print("3= Multiplication")
print("4=Division")

choice = int(input("Enter Choice = "))

num1 = float(input(" First Number: "))
num2 = float(input("Second Number: "))

if choice == 1:
    print("Result =", add(num1, num2))

elif choice == 2:
    print("Result =", subtract(num1, num2))

elif choice == 3:
    print("Result =", multiply(num1, num2))

elif choice == 4:
    print("Result =", divide(num1, num2))

else:
    print("Invalid Choice")

# Store student details in  a file

name = input("Enter Student Name: ")
age=int(input("enter age"))
marks = input("Enter Marks: ")

file = open("student.txt", "w")

file.write("Name: " + name + "\n")
file.write("age: " + age + "\n")
file.write("Marks: " + marks + "\n")

file.close()

print("Studently details are saved  successful")

# Reading File

file = open("student.txt", "r")
data = file.read()
print(data)
file.close()

# Exception Handling

try:
    n1 = int(input("First Number: "))
    n2 = int(input(" Second Number: "))

    result = n1 / n2

    print("Result =", result)

except ZeroDivisionError:
    print(" Division by Zero is Not Allowed")

# Student Class

class Student:

    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def display(self):
        print("Name is", self.name)
        print("Marks are", self.marks)

name = input("Enter Student Name: ")
marks = float(input("Enter Marks: "))

student1 = Student(name, marks)

student1.display()