# -*- coding: utf-8 -*-
"""Assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HGfNqk0qWlMfNYFV0Fu02ViQy3HjhnRV
"""

# Sum of First 10 Natural Numbers

sum = 0

for i in range(1, 11):
    sum = sum + i;

print("Sum of first 10 natural numbers is", sum)

# FindindFactorial of a Number

num = int(input("Enter a number="))

fact = 1

for i in range(1, num + 1):
    fact = fact * i

print("Factorial =", fact)

# Fibonacci Series

n = int(input("Enter number of terms: "))

a = 0
b = 1

print("Fibonacci Series=")

for i in range(n):
    print(a, end=" ")
    c = a + b
    a = b
    b = c

# Finding Largest Among 3 Numbers

num1 = float(input("first number: "))
num2 = float(input(" second number: "))
num3 = float(input(" third number: "))

if num1 >= num2 and num1 >= num3:
    largest = num1

elif num2 >= num1 and num2 >= num3:
    largest = num2

else:
    largest = num3

print("Largest number =", largest)

# Student Result System

#  Student Details
name = input("Enter Student Name: ")
rollno = input("Enter Roll Number: ")

# Number of Subjects
n = int(input("Enter Number of Subjects: "))

total = 0

#  Input Marks
for i in range(1, n + 1):
    marks = float(input(f"Enter Marks of Subject {i}: "))
    total += marks

# Percentage Calculation
percentage = total / n

# Grade Calculation
if percentage >= 93:
    grade = "A+"

elif percentage >= 86:
    grade = "A"

elif percentage >= 75:
    grade = "B"

elif percentage >= 60:
    grade = "C"

elif percentage >= 50:
    grade = "D"

else:
    grade = "Fail"

# Display Result
print("STUDENT RESULT ")
print("Student Name :", name)
print("Roll Number  :", rollno)
print("Total Marks  :", total)
print("Percentage   :", percentage)
print("Grade        :", grade)