# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5URKVQVYUMPcRfSHW3hivKkdVb5zSnH
"""

#1) Area of Rectangle

length = float(input("Enter length= "))
breadth = float(input("Enter breadth= "))

area = length * breadth

print("Area of Rectangle is", area)

# 2)Finding Simple Interest

principal = float(input(" Principal Amount: "))
rate = float(input(" Rate of Interest: "))
time = float(input(" Time (years): "))

SI= (principal * rate * time) / 100

print("Simple Interest is", SI)

# 3)Conversion Celsius to Fahrenheit

celsius = float(input("Enter Temperature in Celsius= "))

fahrenheit = (celsius * 9/5) + 32

print("Temperature in Fahrenheit is", fahrenheit)

# 4)Finding Average of 3 Numbers

n1 = float(input(" First Number: "))
n2 = float(input(" Second Number: "))
n3 = float(input(" Third Number: "))

average = (n1 + n2 + n3) / 3

print("Average is", average)

# 5)Finding Square and Cube

num = int(input("Enter a Number= "))

sq = num ** 2
cube = num ** 3

print("Square =", sq)
print("Cube =", cube)

# Swap Without Third Variable

a = int(input("First Number: "))
b = int(input("Second Number: "))

print("Before Swapping-")
print("a =", a)
print("b =", b)

a, b = b, a

print("After Swapping-")
print("a =", a)
print("b =", b)

# Student Report Program

# Input Student Details
name = input(" Student Name: ")
rollno = input(" Roll Number: ")

# Input Marks
mark1 = float(input(" Marks in maths: "))
mark2 = float(input(" Marks in science: "))
mark3 = float(input(" Marks in English: "))


# Calculate Total
total = mark1 + mark2 + mark3

# Calculate Percentage
percentage = total / 3

# Display Report
print("STUDENT REPORT ")
print("Student Name :", name)
print("Roll Number  :", rollno)

print("\nMarks")
print("maths :", mark1)
print("science:", mark2)
print("English:", mark3)


print("\nTotal Marks =", total)
print("Percentage =", percentage, "%")

# Grade Calculation
if percentage >= 93:
    grade = "A+"
elif percentage >= 86:
    grade = "A"
elif percentage >= 75:
    grade = "B"
elif percentage >= 65:
    grade = "C"
elif percentage >= 50:
    grade = "D"
else:
    grade = "Fail"

print("Grade =", grade)