# -*- coding: utf-8 -*-
"""Vijaya_Assignment_1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TEKluyPgiGgdfE60_iznA83yDuDpcYn
"""

#Q1
l=int(input("ENTER LENGTH:"))
b=int(input("ENTER BREADTH:"))

print("Area:",l*b)

#Q2
interest=int(input("ENTER INTEREST:"))
principal=int(input("ENTER PRINCIPAL:"))
time=int(input("ENTER TIME:"))
si=(interest*principal*time)/100
print("SIMPLE INTEREST:",si)

#Q3
cel=float(input("ENTER TEMPERATURE IN CELSIUS:"))
fahrenheit=(cel*9/5)+32
print("TEMPERATURE IN FAHRENHEIT:",fahrenheit)

#Q4
a=int(input("ENTER FIRST NUMBER:"))
b=int(input("ENTER SECOND NUMBER:"))
c=int(input("ENTER THIRD NUMBER:"))
d=(a+b+c)/3
print("Mean:",d)

#Q5
m=int(input("ENTER:"))
n=int(input("ENTER:"))
sq=m**2
cube=n**3
print("SQUARE:",sq)
print("CUBE:",cube)

#Q6
x=int(input("ENTER FIRST NUMBER:"))
y=int(input("ENTER SECOND NUMBER:"))
x,y=y,x
print("x= ",x,"y= ",y)

#Q7
name=input("ENTER Student's Name:")
science_marks=int(input("ENTER SCIENCE MARKS:"))
maths_marks=int(input("ENTER MATHS MARKS:"))
english_marks=int(input("ENTER ENGLISH MARKS:"))
total_marks=science_marks+maths_marks+english_marks
percentage=(total_marks/300)*100
print("Student's Name:",name)
print("Total Marks:",total_marks)
print("Percentage:",percentage)