# -*- coding: utf-8 -*-
"""Assignment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CPkA6toq5ypWG-19mnMa0OWs2cxS3z-j
"""

#Question 1
length=int(input("Enter the length of rectangle: "))
breadth=int(input("Enter the breadth of rectangle: "))
area=length*breadth
print("Area of rectangle is: ",area)
#Question 2
principle=int(input("Enter the principle amount: "))
time=int(input("Enter the time period in years: "))
rate=int(input("Enter the rate of interest: "))
SI=(principle*time*rate)/100
print("Simple interest is: ",SI)
#Question3
ctemp=int(input("Enter the temperature in celcius: "))
ftemp=(ctemp*(9/5))+32
print("Temperature in Fahrenheit is: ",ftemp)
#Question4
num1=int(input("Enter the first number: "))
num2=int(input("Enter the second number: "))
num3=int(input("Enter the third number: "))
avg=(num1+num2+num3)/3
print("Average of",num1,num2,num3,"is",avg)
#Question5
num=int(input("Enter the number:"))
square=num**2
cube=num**3
print("Square of", num, "is", square)
print("Cube of",num, "is", cube)
#Question6
numb1=int(input("Enter the first number: "))
numb2=int(input("Enter the second number: "))
numb1=numb1+numb2
numb2=numb1-numb2
numb1=numb1-numb2
print("The first number now is",numb1)
print("The second number now is",numb2)
#Question7
roll_no=int(input("Enter student roll number:"))
name=input("Enter  student name: ")
marks1=float(input("Enter marks of subject 1: "))
marks2=float(input("Enter marks of subject 2: "))
marks3=float(input("Enter marks of subject 3: "))
marks4=float(input("Enter marks of subject 4: "))
marks5=float(input("Enter marks of subject 5: "))
total_marks=marks1+marks2+marks3+marks4+marks5
percentage=(total_marks/500)*100
print("Roll number: 9",roll_no,"\n Student Name:",name, "\n has total marks of",total_marks,"and percentage of ",percentage)