# -*- coding: utf-8 -*-
"""Assignment 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MS__Zm8J_iZ3zzYrggrCpun5J_6V-UVj
"""

#Question 1
sum=0
for i in range(1,11):
  sum=sum+i
print("Sum of first 10 natural numbers is: ",sum)
#Question 2
num =int(input("Enter non negative number whose factorial has to be found"))
fact = 1
for i in range (1,num+1) :
  fact = fact*(i)
print ("factorial of ",num,"is",fact)
#Question 3
a=0
b=1
number=int(input("Enter the number of terms for which you want to calculate the fibbonacci series: "))
print(a)
print(b)
for i in range(0,number-2):
  c=a+b
  a=b
  b=c
  print(c)
#Question 4
num1=int(input("Enter the first number: "))
num2=int(input("Enter the second number: "))
num3=int(input("Enter the third number: "))
if num1>num2 and num1>num3:
  print(num1, "is largest")
elif num2>num1 and num2>num3:
  print(num2, "is largest")
else:
  print(num3, "is largest")

#Question 5
roll_no=int(input("Enter student roll number:"))
name=input("Enter  student name: ")
sum1=0
count=0
while  (True):
  marks=float(input("Enter marks of subject: "))
  sum1=sum1+marks
  count+=1
  wish=input("Do you wish to enter marks for more subject: ")
  if wish=="no" or wish=="NO" or wish=="No":
    break
percentage=(sum1/(count*100))*100
print("Roll number: ",roll_no,"\n Student Name:",name, "\n has total marks of",sum1,"and percentage of ",percentage)
if percentage>=93:
  print("Grade A+")
elif percentage>=85 and percentage<93:
  print("Grade A")
elif percentage>=77 and percentage<85 :
  print("Grade B")
elif percentage>=65 and percentage<77:
  print("Grade C")
elif percentage>=45 and percentage<65:
  print("Grade D")
else:
  print("Fail")