# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nb2h04Fvrr8-UmucMuWQwBbZwetf-XIf
"""

#1 Function to Print First 10 Natural Numbers
def print_numbers():
    for i in range(1, 11):
        print(i)

print_numbers()

#2 Function to Calculate Sum of First N Natural Numbers
def sum_natural(n):
    total = 0
    for i in range(1, n + 1):
        total += i
    return total

n = int(input("Enter N: "))
print("Sum =", sum_natural(n))

#3 Function to Reverse a Number
def reverse_number(num):
    rev = 0

    while num > 0:
        digit = num % 10
        rev = rev * 10 + digit
        num = num // 10

    return rev

num = int(input("Enter a number: "))
print("Reversed Number =", reverse_number(num))

#4 Function to Count Digits in a Number
def count_digits(num):
    count = 0

    while num > 0:
        count += 1
        num = num // 10

    return count

num = int(input("Enter a number: "))
print("Number of digits =", count_digits(num))

#5 Function to Check Palindrome Number
def palindrome(num):
    original = num
    rev = 0

    while num > 0:
        digit = num % 10
        rev = rev * 10 + digit
        num = num // 10

    if original == rev:
        return True
    else:
        return False

num = int(input("Enter a number: "))

if palindrome(num):
    print("Palindrome Number")
else:
    print("Not a Palindrome Number")

#6 Function to Generate Fibonacci Series
def fibonacci(n):
    a = 0
    b = 1

    for i in range(n):
        print(a, end=" ")
        c = a + b
        a = b
        b = c

n = int(input("Enter number of terms: "))
fibonacci(n)

#7 Calculator Using Functions
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    return a / b

print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")

choice = int(input("Enter your choice (1-4): "))

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

if choice == 1:
    print("Result =", add(num1, num2))

elif choice == 2:
    print("Result =", subtract(num1, num2))

elif choice == 3:
    print("Result =", multiply(num1, num2))

elif choice == 4:
    if num2 != 0:
        print("Result =", divide(num1, num2))
    else:
        print("Division by zero is not possible")

else:
    print("Invalid Choice")